# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: UL Solutions Coding Challenge Pipeline

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

env:
  SOLUTION_PATH: ./ExpressionEvaluatorAPI/ExpressionEvaluatorAPI.sln

permissions:
    contents: read
    actions: read
    checks: write 

jobs:
   
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore  ${{ env.SOLUTION_PATH }}
    - name: Build
      run: dotnet build  ${{ env.SOLUTION_PATH }} --configuration Release --no-restore
    - name: Test
      run: dotnet test  ${{ env.SOLUTION_PATH }} --configuration Release  --no-restore --no-build --verbosity normal #--logger "trx;LogFileName=test-results.trx" 
    - name: Publish
      run: dotnet publish ${{ env.SOLUTION_PATH }} --configuration Release  --no-restore --no-build 
    - name: Test Reporting
      uses: phoenix-actions/test-reporting@v12


    # - name: Test Report
    #   uses: dorny/test-reporter@v1
    #   if: always()
    #   with:
    #     name: xUnit Tests
    #     path: "**/test-results.trx"
    #     reporter: dotnet-trx
    #     fail-on-error: true

      
